made changes to work independently of the html files, but I simply do not have the compute to run the program.
here is the error:
(chemgen) (base) tylergee@Tylers-MacBook-Pro ChemGen % /Users/tylergee/anaconda3/envs/chemgen/bin/python /Users/tylergee/Documents
/ChemGen/app.py
MLX initialized (GPU should be used on Apple Silicon)
Loaded 392446 reactions from data/uspto_reactions.csv
Traceback (most recent call last):
  File "/Users/tylergee/Documents/ChemGen/app.py", line 57, in <module>
    padded_sequences = [pad_sequence(seq, max_length) for seq in encoded_sequences]
  File "/Users/tylergee/Documents/ChemGen/app.py", line 57, in <listcomp>
    padded_sequences = [pad_sequence(seq, max_length) for seq in encoded_sequences]
  File "/Users/tylergee/Documents/ChemGen/app.py", line 54, in pad_sequence
    return mx.pad(seq_array, pad_width=pad_width, mode='constant', constant_values=0)
RuntimeError: [metal::malloc] Resource limit (499000) exceeded.